[2025-03-13T15:55:35.112+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-13T15:55:35.131+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: web_scraping_dag.trigger_parse_dag manual__2025-03-13T15:55:31.703506+00:00 [queued]>
[2025-03-13T15:55:35.140+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: web_scraping_dag.trigger_parse_dag manual__2025-03-13T15:55:31.703506+00:00 [queued]>
[2025-03-13T15:55:35.141+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 5
[2025-03-13T15:55:35.152+0000] {taskinstance.py:2890} INFO - Executing <Task(TriggerDagRunOperator): trigger_parse_dag> on 2025-03-13 15:55:31.703506+00:00
[2025-03-13T15:55:35.159+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'web_scraping_dag', 'trigger_parse_dag', 'manual__2025-03-13T15:55:31.703506+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/Website2mongo.py', '--cfg-path', '/tmp/tmp_52oga1g']
[2025-03-13T15:55:35.161+0000] {standard_task_runner.py:105} INFO - Job 70: Subtask trigger_parse_dag
[2025-03-13T15:55:35.161+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5484) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-13T15:55:35.162+0000] {standard_task_runner.py:72} INFO - Started process 5485 to run task
[2025-03-13T15:55:35.196+0000] {task_command.py:467} INFO - Running <TaskInstance: web_scraping_dag.trigger_parse_dag manual__2025-03-13T15:55:31.703506+00:00 [running]> on host 40f8d416e5ba
[2025-03-13T15:55:35.270+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='web_scraping_dag' AIRFLOW_CTX_TASK_ID='trigger_parse_dag' AIRFLOW_CTX_EXECUTION_DATE='2025-03-13T15:55:31.703506+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-13T15:55:31.703506+00:00'
[2025-03-13T15:55:35.271+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-13T15:55:35.461+0000] {trigger_dagrun.py:257} INFO - Waiting for parse_mongo_to_sql_dag on 2025-03-13 15:55:35.287686+00:00 to become allowed state ['success'] ...
[2025-03-13T15:56:40.933+0000] {trigger_dagrun.py:257} INFO - Waiting for parse_mongo_to_sql_dag on 2025-03-13 15:55:35.287686+00:00 to become allowed state ['success'] ...
[2025-03-13T15:57:46.400+0000] {trigger_dagrun.py:257} INFO - Waiting for parse_mongo_to_sql_dag on 2025-03-13 15:55:35.287686+00:00 to become allowed state ['success'] ...
[2025-03-13T15:58:51.869+0000] {trigger_dagrun.py:257} INFO - Waiting for parse_mongo_to_sql_dag on 2025-03-13 15:55:35.287686+00:00 to become allowed state ['success'] ...
[2025-03-13T15:59:57.343+0000] {trigger_dagrun.py:257} INFO - Waiting for parse_mongo_to_sql_dag on 2025-03-13 15:55:35.287686+00:00 to become allowed state ['success'] ...
[2025-03-13T16:01:02.813+0000] {trigger_dagrun.py:257} INFO - Waiting for parse_mongo_to_sql_dag on 2025-03-13 15:55:35.287686+00:00 to become allowed state ['success'] ...
[2025-03-13T16:02:08.282+0000] {trigger_dagrun.py:257} INFO - Waiting for parse_mongo_to_sql_dag on 2025-03-13 15:55:35.287686+00:00 to become allowed state ['success'] ...
[2025-03-13T16:03:13.754+0000] {trigger_dagrun.py:257} INFO - Waiting for parse_mongo_to_sql_dag on 2025-03-13 15:55:35.287686+00:00 to become allowed state ['success'] ...
[2025-03-13T16:04:19.237+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/trigger_dagrun.py", line 269, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: parse_mongo_to_sql_dag failed with failed states failed
[2025-03-13T16:04:19.244+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=web_scraping_dag, task_id=trigger_parse_dag, run_id=manual__2025-03-13T15:55:31.703506+00:00, execution_date=20250313T155531, start_date=20250313T155535, end_date=20250313T160419
[2025-03-13T16:04:19.269+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-13T16:04:19.270+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 70 for task trigger_parse_dag (parse_mongo_to_sql_dag failed with failed states failed; 5485)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/trigger_dagrun.py", line 269, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: parse_mongo_to_sql_dag failed with failed states failed
[2025-03-13T16:04:19.300+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-13T16:04:19.319+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-13T16:04:19.321+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
